version: '3.5'

services:
  taskforce.account.mongo:
    image: mongo
    restart: always
    container_name: taskforce.account.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}

    ports:
      - 27017:27017

    volumes:
      - taskforce.account.mongo:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/taskforce-account --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  taskforce.account.mongo.admin:
    image: mongo-express
    restart: always
    container_name: taskforce.account.mongo.admin
    ports:
      - 8081:8081
    depends_on:
      - taskforce.account.mongo
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@taskforce.account.mongo:27017/

volumes:
  taskforce.account.mongo:
