### Variables
@port = 3333
@apiPrefix = api
@apiVersion = v1
@service = reviews
@taskId = 627a6872-29dd-4869-af2e-7df28a82aa6c

#####################################################################

### 
## Добавление отзыва
POST  http://localhost:{{port}}/{{apiPrefix}}/{{apiVersion}}/{{service}} HTTP/1.1
content-type: application/json

{
    "text": "Some review text",
    "task": "627a6872-29dd-4869-af2e-7df28a82aa6c",
    "rating": 5
}
